spring:
  application:
    name: SulRoom

  # mail
  mail:
    host: smtp.naver.com
    port: 465
    username: jh950925
    password: dustp@025
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          ssl:
            enable: true

  #redis
  data:
    redis:
      host: localhost
      port: 6379
