spring:
  application:
    name: SulRoom
  # MYSQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sulroom
    username: jh950925
    password: rla123

  #thymeleaf
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    cache: false
  # JPA
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
  # mail
#  mail:
#    host: smtp.naver.com
#    port: 465
#    username: jh950925
#    password: dustp@025
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: true
#          auth: true
#          ssl:
#            enable: true
  #redis
#  data:
#    redis:
#      host: localhost
#      port: 6379

#mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: jh.sulroom.sulroom.app.model.entity.user
  mapper-locations: classpath:mappers/*.xml


